extends Node

const SHOT_CLEARANCE: int = 15
const DUEL_SCENE_PATH: String = "res://scenes/Game Scenes/RealBallDuel.tscn"
const HOW_TO_PLAY_SCENE_PATH: String = "res://scenes/Game Scenes/HowToPlay.tscn"
const MAIN_MENU_PATH: String = "res://scenes/Game Scenes/MainMenu.tscn"
const BULLET_TYPES_PATH: String = "res://scenes/Game Scenes/HowToPlayBulletTypes.tscn"

const EASY: String = "Easy"
const MEDIUM: String = "Medium"
const HARD: String = "Hard"
const INSANE: String = "INSANE"

const PLAYER_LIVES_EASY: int = 7
const PLAYER_LIVES_MEDIUM: int = 5
const PLAYER_LIVES_HARD: int = 3
const PLAYER_LIVES_INSANE: int = 1

const AI_LIVES_EASY: int = 5
const AI_LIVES_MEDIUM: int = 5
const AI_LIVES_HARD: int = 5
const AI_LIVES_INSANE: int = 5

const BOSS_LIVES_EASY: int = 1
const BOSS_LIVES_MEDIUM: int = 2
const BOSS_LIVES_HARD: int = 3
const BOSS_LIVES_INSANE: int = 3

const BALL_DANGEROUS_THROTTLE_EASY: float = 0.95
const BALL_DANGEROUS_THROTTLE_MEDIUM: float = 0.95
const BALL_DANGEROUS_THROTTLE_HARD: float = 0.95
const BALL_DANGEROUS_THROTTLE_INSANE: float = 0.95

const BALL_BOUNCE_SPEED_MULITPLIER_EASY: float = 1.04
const BALL_BOUNCE_SPEED_MULITPLIER_MEDIUM: float = 1.04
const BALL_BOUNCE_SPEED_MULITPLIER_HARD: float = 1.04
const BALL_BOUNCE_SPEED_MULITPLIER_INSANE: float = 1.04

const BALL_SPEED_EASY: int = 600
const BALL_SPEED_MEDIUM: int = 800
const BALL_SPEED_HARD: int = 600
const BALL_SPEED_INSANE: int = 600

const BALL_DANGEROUS_SPEED_EASY: int = 1400
const BALL_DANGEROUS_SPEED_MEDIUM: int = 1400
const BALL_DANGEROUS_SPEED_HARD: int = 1400
const BALL_DANGEROUS_SPEED_INSANE: int = 1400

const PONG_PADDLE_SPEED_EASY: int = 400
const PONG_PADDLE_SPEED_MEDIUM: int = 600
const PONG_PADDLE_SPEED_HARD: int = 600
const PONG_PADDLE_SPEED_INSANE: int = 600

const FAKE_PADDLE_SPEED_EASY: int = 400
const FAKE_PADDLE_SPEED_MEDIUM: int = 500
const FAKE_PADDLE_SPEED_HARD: int = 600
const FAKE_PADDLE_SPEED_INSANE: int = 700

const BULLET_PADDLE_SPEED_EASY: int = 600
const BULLET_PADDLE_SPEED_MEDIUM: int = 600
const BULLET_PADDLE_SPEED_HARD: int = 600
const BULLET_PADDLE_SPEED_INSANE: int = 600

const STEALTH_PADDLE_SPEED_EASY: int = 600
const STEALTH_PADDLE_SPEED_MEDIUM: int = 600
const STEALTH_PADDLE_SPEED_HARD: int = 600
const STEALTH_PADDLE_SPEED_INSANE: int = 600

const FAKE_BALL_AMOUNT_EASY: int = 10
const FAKE_BALL_AMOUNT_MEDIUM: int = 10
const FAKE_BALL_AMOUNT_HARD: int = 10
const FAKE_BALL_AMOUNT_INSANE: int = 10

const RAPID_FIRE_AMOUNT_EASY: int = 35
const RAPID_FIRE_AMOUNT_MEDIUM: int = 35
const RAPID_FIRE_AMOUNT_HARD: int = 35
const RAPID_FIRE_AMOUNT_INSANE: int = 35

const RAPID_FIRE_RATE_EASY: int = 150
const RAPID_FIRE_RATE_MEDIUM: int = 150
const RAPID_FIRE_RATE_HARD: int = 150
const RAPID_FIRE_RATE_INSANE: int = 150

const RAPID_FIRE_SPEED_EASY: int = 1000
const RAPID_FIRE_SPEED_MEDIUM: int = 1000
const RAPID_FIRE_SPEED_HARD: int = 1000
const RAPID_FIRE_SPEED_INSANE: int = 1000

const STEALTH_BALL_SPEED_EASY: int = 1000
const STEALTH_BALL_SPEED_MEDIUM: int = 1000
const STEALTH_BALL_SPEED_HARD: int = 1000
const STEALTH_BALL_SPEED_INSANE: int = 1000

const BOSS_BALL_DANGEROUS_THROTTLE_EASY: float = 0.95
const BOSS_BALL_DANGEROUS_THROTTLE_MEDIUM: float = 0.95
const BOSS_BALL_DANGEROUS_THROTTLE_HARD: float = 0.95
const BOSS_BALL_DANGEROUS_THROTTLE_INSANE: float = 0.95

const BOSS_FAKE_BALL_AMOUNT_EASY: int = 10
const BOSS_FAKE_BALL_AMOUNT_MEDIUM: int = 10
const BOSS_FAKE_BALL_AMOUNT_HARD: int = 10
const BOSS_FAKE_BALL_AMOUNT_INSANE: int = 10

const BOSS_RAPID_FIRE_AMOUNT_EASY: int = 35
const BOSS_RAPID_FIRE_AMOUNT_MEDIUM: int = 35
const BOSS_RAPID_FIRE_AMOUNT_HARD: int = 35
const BOSS_RAPID_FIRE_AMOUNT_INSANE: int = 35

const BOSS_RAPID_FIRE_RATE_EASY: int = 150
const BOSS_RAPID_FIRE_RATE_MEDIUM: int = 150
const BOSS_RAPID_FIRE_RATE_HARD: int = 150
const BOSS_RAPID_FIRE_RATE_INSANE: int = 150

const BOSS_RAPID_FIRE_SPEED_EASY: int = 1000
const BOSS_RAPID_FIRE_SPEED_MEDIUM: int = 1000
const BOSS_RAPID_FIRE_SPEED_HARD: int = 1000
const BOSS_RAPID_FIRE_SPEED_INSANE: int = 1000

const BOSS_STEALTH_BALL_SPEED_EASY: int = 1000
const BOSS_STEALTH_BALL_SPEED_MEDIUM: int = 1000
const BOSS_STEALTH_BALL_SPEED_HARD: int = 1000
const BOSS_STEALTH_BALL_SPEED_INSANE: int = 1000
