extends Node

const SHOT_CLEARANCE: int = 15
const DUEL_SCENE_PATH: String = "res://scenes/Game Scenes/RealBallDuel.tscn"
const HOW_TO_PLAY_SCENE_PATH: String = "res://scenes/Game Scenes/HowToPlay.tscn"
const MAIN_MENU_PATH: String = "res://scenes/Game Scenes/MainMenu.tscn"
const BULLET_TYPES_PATH: String = "res://scenes/Game Scenes/HowToPlayBulletTypes.tscn"

const EASY: String = "Easy"
const MEDIUM: String = "Medium"
const HARD: String = "Hard"
const INSANE: String = "INSANE"

const PLAYER_LIVES_EASY: int = 5
const PLAYER_LIVES_MEDIUM: int = 5
const PLAYER_LIVES_HARD: int = 5
const PLAYER_LIVES_INSANE: int = 5

const AI_LIVES_EASY: int = 5
const AI_LIVES_MEDIUM: int = 5
const AI_LIVES_HARD: int = 5
const AI_LIVES_INSANE: int = 5

const BOSS_LIVES_EASY: int = 3
const BOSS_LIVES_MEDIUM: int = 3
const BOSS_LIVES_HARD: int = 3
const BOSS_LIVES_INSANE: int = 3

const BALL_DANGEROUS_THROTTLE_EASY: float = 0.75
const BALL_DANGEROUS_THROTTLE_MEDIUM: float = 0.75
const BALL_DANGEROUS_THROTTLE_HARD: float = 0.75
const BALL_DANGEROUS_THROTTLE_INSANE: float = 0.75

const BALL_BOUNCE_SPEED_MULITPLIER_EASY: float = 1.04
const BALL_BOUNCE_SPEED_MULITPLIER_MEDIUM: float = 1.05
const BALL_BOUNCE_SPEED_MULITPLIER_HARD: float = 1.06
const BALL_BOUNCE_SPEED_MULITPLIER_INSANE: float = 1.07

const BALL_SPEED_EASY: int = 550
const BALL_SPEED_MEDIUM: int = 650
const BALL_SPEED_HARD: int = 750
const BALL_SPEED_INSANE: int = 850

const BALL_DANGEROUS_SPEED_EASY: int = 800
const BALL_DANGEROUS_SPEED_MEDIUM: int = 1200
const BALL_DANGEROUS_SPEED_HARD: int = 1400
const BALL_DANGEROUS_SPEED_INSANE: int = 1500

const PONG_PADDLE_SPEED_EASY: int = 400
const PONG_PADDLE_SPEED_MEDIUM: int = 500
const PONG_PADDLE_SPEED_HARD: int = 600
const PONG_PADDLE_SPEED_INSANE: int = 700

const FAKE_PADDLE_SPEED_EASY: int = 450
const FAKE_PADDLE_SPEED_MEDIUM: int = 550
const FAKE_PADDLE_SPEED_HARD: int = 650
const FAKE_PADDLE_SPEED_INSANE: int = 750

const BULLET_PADDLE_SPEED_EASY: int = 400
const BULLET_PADDLE_SPEED_MEDIUM: int = 500
const BULLET_PADDLE_SPEED_HARD: int = 600
const BULLET_PADDLE_SPEED_INSANE: int = 700

const STEALTH_PADDLE_SPEED_EASY: int = 400
const STEALTH_PADDLE_SPEED_MEDIUM: int = 500
const STEALTH_PADDLE_SPEED_HARD: int = 650
const STEALTH_PADDLE_SPEED_INSANE: int = 700

const FAKE_BALL_AMOUNT_EASY: int = 6
const FAKE_BALL_AMOUNT_MEDIUM: int = 12
const FAKE_BALL_AMOUNT_HARD: int = 18
const FAKE_BALL_AMOUNT_INSANE: int = 24

const ATTACK_THROTTLE_EASY: float = 0.70
const ATTACK_THROTTLE_MEDIUM: float = 0.80
const ATTACK_THROTTLE_HARD: float = 0.90
const ATTACK_THROTTLE_INSANE: float = 1.0

const RAPID_FIRE_AMOUNT_EASY: int = 45
const RAPID_FIRE_AMOUNT_MEDIUM: int = 75
const RAPID_FIRE_AMOUNT_HARD: int = 105
const RAPID_FIRE_AMOUNT_INSANE: int = 135

# in Hz
const RAPID_FIRE_RATE_EASY: int = 4
const RAPID_FIRE_RATE_MEDIUM: int = 10
const RAPID_FIRE_RATE_HARD: int = 14
const RAPID_FIRE_RATE_INSANE: int = 22

const STEALTH_BALL_SPEED_EASY: int = 800
const STEALTH_BALL_SPEED_MEDIUM: int = 1000
const STEALTH_BALL_SPEED_HARD: int = 1200
const STEALTH_BALL_SPEED_INSANE: int = 1400

const STEALTH_BALL_ACCEPTABLE_DELAY_EASY: float = 1.0
const STEALTH_BALL_ACCEPTABLE_DELAY_MEDIUM: float = .75
const STEALTH_BALL_ACCEPTABLE_DELAY_HARD: float = 0.50
const STEALTH_BALL_ACCEPTABLE_DELAY_INSANE: float = 0.25

const BOSS_BALL_DANGEROUS_THROTTLE_EASY: float = 0.80
const BOSS_BALL_DANGEROUS_THROTTLE_MEDIUM: float = 0.85
const BOSS_BALL_DANGEROUS_THROTTLE_HARD: float = 0.90
const BOSS_BALL_DANGEROUS_THROTTLE_INSANE: float = 0.95

const BOSS_FAKE_BALL_AMOUNT_EASY: int = 10
const BOSS_FAKE_BALL_AMOUNT_MEDIUM: int = 16
const BOSS_FAKE_BALL_AMOUNT_HARD: int = 22
const BOSS_FAKE_BALL_AMOUNT_INSANE: int = 28

const BOSS_ATTACK_THROTTLE_EASY: float = 0.75
const BOSS_ATTACK_THROTTLE_MEDIUM: float = 0.85
const BOSS_ATTACK_THROTTLE_HARD: float = 0.95
const BOSS_ATTACK_THROTTLE_INSANE: float = 1.05

const BOSS_RAPID_FIRE_AMOUNT_EASY: int = 60
const BOSS_RAPID_FIRE_AMOUNT_MEDIUM: int = 90
const BOSS_RAPID_FIRE_AMOUNT_HARD: int = 120
const BOSS_RAPID_FIRE_AMOUNT_INSANE: int = 150

const BOSS_RAPID_FIRE_RATE_EASY: int = 6
const BOSS_RAPID_FIRE_RATE_MEDIUM: int = 12
const BOSS_RAPID_FIRE_RATE_HARD: int = 16
const BOSS_RAPID_FIRE_RATE_INSANE: int = 24

const BOSS_STEALTH_BALL_SPEED_EASY: int = 900
const BOSS_STEALTH_BALL_SPEED_MEDIUM: int = 1100
const BOSS_STEALTH_BALL_SPEED_HARD: int = 1300
const BOSS_STEALTH_BALL_SPEED_INSANE: int = 1500
